# .github/workflows/frontend-tests.yml
name: Frontend Build and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: Node.js installieren
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Abhängigkeiten installieren
      run: npm install

    - name: Lint prüfen
      run: npm run lint

    - name: Build testen
      run: npm run build
